---
- name: FI sample output
  hosts: all
  gather_facts: no

  tasks:
  # 
  # Collect data
  #
  - name: run cli commands
    ansible.netcommon.cli_command:
	  command: show version
	register: result

