
---
- name: Collect NXOS interface status from network device
  hosts: all
  gather_facts: no

  tasks:
    - name: Connect to NXOS shell
      ansible.builtin.raw: "connect nxos"
      register: nxos_connect
      changed_when: false
      failed_when: false

    - name: Run 'show interface status'
      ansible.builtin.raw: "show interface status"
      register: nxos_interface_status
      changed_when: false
      failed_when: false

    - name: Display captured output
      debug:
        msg: "{{ nxos_interface_status.stdout }}"
