
---
- name: Run NXOS show in one line
  ansible.builtin.raw: "connect nxos a ; show interface status ; exit"
  register: nxos_output
  changed_when: false
  failed_when: false

- name: Display captured output
  debug:
    msg: "{{ nxos_output.stdout }}"


