
---
- name: SSH connectivity test using raw (check stderr for Cisco UCS)
  hosts: all
  gather_facts: no

  tasks:
    - name: SSH check
      ansible.builtin.raw: "echo ok"   # Or any harmless command
      register: ssh_test
      changed_when: false
      failed_when: false
#      no_log: true   # Optional: hides stdout/stderr completely

    - name: Normalize buffers for evaluation
      ansible.builtin.set_fact:
        ssh_stdout: "{{ ssh_test.stdout | default('') }}"
        ssh_stderr: "{{ ssh_test.stderr | default('') }}"
