
---
- name: SSH connectivity test using raw (no remote python required)
  hosts: all
  gather_facts: no

  tasks:
    - name: Run a simple SSH test (no remote python required)
      ansible.builtin.raw: "echo ok"
      register: ssh_test
      changed_when: false
      failed_when: false

    - name: Normalize buffers for evaluation
      ansible.builtin.set_fact:
        ssh_stdout: "{{ ssh_test.stdout | default('') }}"
        ssh_stderr: "{{ ssh_test.stderr | default('') }}"
        ssh_rc: "{{ ssh_test.rc | default(0) }}"

    - name: Assert SSH connectivity worked (FI-friendly)
      ansible.builtin.assert:
        that:
          - ssh_rc == 0
          - ssh_stderr | regex_search('Shared connection.*closed', ignorecase=True) is not defined
            or (ssh_stderr | length) >= 0
          # Accept typical FI banners/errors:
          - ssh_stdout | length >= 0
        success_msg: >-
          SUCCESS on {{ inventory_hostname }} ({{ ansible_host | default(inventory_hostname) }})
          rc={{ ssh_rc }}, stdout={{ ssh_stdout | truncate(120) }}, stderr={{ ssh_stderr | truncate(120) }}
        fail_msg: >-
          FAILED SSH to {{ inventory_hostname }}:
          rc={{ ssh_rc }}, stdout={{ ssh_stdout }}, stderr={{ ssh_stderr }

