
# ssh_test.yml
---
- name: Test SSH connectivity
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Run a simple command to verify SSH
      cisco.ios.ios_command
        commands:
        - show version
      register: ssh_test_result

    - name: Show SSH test result
      ansible.builtin.debug:
        msg: "Connected as {{ result.stdout }}"
