
---
- name: SSH connectivity test using raw (check stderr for Cisco UCS)
  hosts: all
  gather_facts: no

  tasks:
    - name: SSH check
      ansible.builtin.raw: "echo ok"   # Or any harmless command
      register: ssh_test
      changed_when: false
      failed_when: >
        (ssh_test.rc | default(1)) != 0
        or ('Cisco UCS' not in (ssh_test.stderr | default('')))
      no_log: true   # Optional: hides stdout/stderr completely
