--- #YAML document start marker
- name: SSH connectivity test using raw (no remote python required) #Play name
  hosts: all #The Play runs agains all hosts
  gather_facts: no #Speeds up execution

# Regarding ansible.builtin.raw:
# This is a module of Ansible core (ansible-core) and is included on all Ansible installations.
# It executes a low-down and dirty SSH command.
# It is commonly used to connect to network devices, as these do not have Python installed. 
# Standard output, error output and return code are returned when available.

  tasks:
    - name: Run a simple SSH connectivity test
      ansible.builtin.raw: "echo ok" # "echo ok" is chosen as it should succeed on any device that offers a standard shell.
      register: ssh_test #Register the task’s result into a variable named ssh_test.
# changed_when and failed_when are set to false. changed_when is N/A as this is a read-only probe. failed_when prevents Ansible from marking this task as failed. This lets you decide success/failure later.
      changed_when: false
      failed_when: false

# Create normalized variables from the previous result.
# ansible.builtin.set_fact saves variables at runtime.
# ssh_stdout: safely pull stdout; if missing, default to empty string.
# ssh_stderr: safely pull stderr; default to empty string.
# ssh_rc: safely pull rc (return code); default to 0 and cast to integer.

    - name: Normalize buffers for evaluation
      ansible.builtin.set_fact:
        ssh_stdout: "{{ ssh_test.stdout | default('') }}"
        ssh_stderr: "{{ ssh_test.stderr | default('') }}"
        ssh_rc: "{{ (ssh_test.rc | default(0)) | int }}"
